#Modify all lines indicated with MODIFY
vcfs:
  1000g:
    '1': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr1.vcf.gz"
    '2': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr2.vcf.gz"
    '3': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr3.vcf.gz"
    '4': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr4.vcf.gz"
    '5': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr5.vcf.gz"
    '6': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr6.vcf.gz"
    '7': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr7.vcf.gz"
    '8': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr8.vcf.gz"
    '9': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr9.vcf.gz"
    '10': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr10.vcf.gz"
    '11': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr11.vcf.gz"
    '12': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr12.vcf.gz"
    '13': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr13.vcf.gz"
    '14': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr14.vcf.gz"
    '15': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr15.vcf.gz"
    '16': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr16.vcf.gz"
    '17': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr17.vcf.gz"
    '18': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr18.vcf.gz"
    '19': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr19.vcf.gz"
    '20': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr20.vcf.gz"
    '21': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr21.vcf.gz"
    '22': "/home/pmonnaha/shared/h1kgdp/h1kgdp_hg38.chr22.vcf.gz"
#    X: "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1b.20130502.genotypes.vcf.gz"
#    Y: "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chrY.phase3_integrated_v2a.20130502.genotypes.vcf.gz"
  AA_spec: "AA_chimp" #What is the INFO label that indicates ancestral allele in the VCFs.  This will be used for polarizing haplotype stats.
input_filters:
  missingness: "0.1"
pop_key: "/home/pmonnaha/pmonnaha/misc/igsr_samples.tsv"
nucleotide_stats:
  within_pop: "pi,tajD,thetaW,r2"
  between_pop: "dxy,FD,Fst_Hud,Fst_Pat"
haplotype_stats:
  within_pop: "iHS,nSL"
  between_pop: "xpehh,xpnSL"
query_pops: "all"
reference_pop: "CEU"
python_virtual_env: "py36"
window_size: "50000"
genetic_map: "/home/pmonnaha/pmonnaha/misc/genetic_map_hg19.txt"
SDS:
  exec: "/home/spectorl/pmonnaha/software/SDS/compute_SDS.R"
  gamma_shapes:
    AFR:
      path: "/home/spectorl/pmonnaha/software/SDS/gamma_shapes.Gravel_AFR.n100"
      pops: "YRI,GWD,ESN,MSL,LWK"
      init: '1e-6'
    EUR:
      path: "/home/spectorl/pmonnaha/software/SDS/gamma_shapes.Tennessen_EUR.n100"
      pops: "CEU,FIN,IBS,TSI"
      init: '1e-6'
    EAS:
      path: "/home/spectorl/pmonnaha/software/SDS/gamma_shapes.Gravel_EAS.n100"
      pops: "CDX,CHB,CHS,JPT,KHV"
      init: '1e-6'
