#Modify all lines indicated with MODIFY
vcfs:
  1000g:
    '1': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '2': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr2.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '3': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr3.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '4': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr4.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '5': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr5.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '6': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr6.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '7': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr7.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '8': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr8.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '9': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr9.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '10': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr10.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '11': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '12': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr12.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '13': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr13.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '14': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr14.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '15': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr15.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '16': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr16.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '17': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr17.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '18': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr18.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '19': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr19.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '20': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '21': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
    '22': "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
#    X: "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1b.20130502.genotypes.vcf.gz"
#    Y: "/home/pankrat2/public/bin/ref/1000G_v5/ALL.chrY.phase3_integrated_v2a.20130502.genotypes.vcf.gz"
pop_key: "/home/pmonnaha/pmonnaha/misc/igsr_samples.tsv"
nucleotide_stats:
  within_pop: "pi,tajD"
  between_pop: "dxy,FD,Fst_Hud,Fst_Pat"
haplotype_stats:
  within_pop: "iHS,nSL"
  between_pop: "xpehh,xpnSL"
query_pops: "all"
reference_pop: "CEU"
python_virtual_env: "py27"
window_size: "50000"
genetic_map: "/home/pmonnaha/pmonnaha/accessory/genetic_map_hg19.txt"
